# Generated by Django 3.1.5 on 2021-01-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInstallmentPlans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('plan_count', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
