# Generated by Django 3.1.5 on 2021-01-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lender', '0002_auto_20210129_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanplans',
            old_name='plan_count',
            new_name='count',
        ),
    ]
